# Generated by Django 4.1.1 on 2022-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_job', models.CharField(help_text='My current job', max_length=15)),
            ],
        ),
    ]
